# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 963fbfa2444cd0f2286fc0e60038ae1fbc76c1557726f493715c32d0211e6955435596c9b732fe748048828b5b6a0f1ce51c96a2f50c523d0cc8d5add308f75f

test:
  secret_key_base: afe966d1e425672877c6bd062a566c15ada87c1159d3dda834953a6df7d6ccb17d599f4dbe0ea571f8f5bc56b5459528111ad81fa8c3ca1d517b9c2351d98b18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
